
trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  dockerId: luoyunchong@foxmail.com            
  namespace: igeekfan                            
  webimageName: lincms-web      
  registry: registry.cn-hangzhou.aliyuncs.com
  linCmsWebdockerfilepath:  src/LinCms.Web/Dockerfile  

steps:
- script: |
    docker build -f $(linCmsWebdockerfilepath) -t $(webimageName) .
    echo $(pwd) | docker login --username $(dockerId) $(registry) --password-stdin
    docker tag $(webimageName) $(registry)/$(namespace)/$(webimageName)
    docker push $(registry)/$(namespace)/$(webimageName)

  displayName: push to lincms-web